In [1]:
import numpy

In [3]:
numpy.__version__

'1.20.1'

In [4]:
import numpy as np

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [11]:
print(a[0])

[1 2 3 4]


In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(2,29,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# Add, Remove, and Sort

In [20]:
arr = np.array([1,2,3,4,5,6,7,8])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [23]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [25]:
arr = np.array([2,1,5,3,7,8])

In [26]:
np.sort(arr)

array([1, 2, 3, 5, 7, 8])

# Reshape

In [29]:
a = np.arange(6)

In [28]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [33]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[0 1 2 3 4 5]]


In [35]:
col_vector = a[: , np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
